###############################################################################
# Licensed Materials - Property of IBM.
# Copyright IBM Corporation 2018. All Rights Reserved.
# U.S. Government Users Restricted Rights - Use, duplication or disclosure
# restricted by GSA ADP Schedule Contract with IBM Corp.
#
# Contributors:
# IBM Corporation - initial API and implementation
###############################################################################
apiVersion: v1
kind: Service
metadata:
  name: db2database
  labels:
    app.kubernetes.io/name: db2database
    component: db2database
    run: db2database
spec:
  type: LoadBalancer
  ports:
  - port: 50000
    targetPort: 50000
    protocol: TCP
    name: db2database
  selector:
    app.kubernetes.io/name: db2database
    component: db2database